### ISSUE TITLE
Errors on all commands

### ISSUE THREAD

**Issue by stopeject** [tiramiseb/python-openevse#5]
I didn't do anything with the openevse plugin for a while. Tried it today, and getting errors on all commands: 
```
gt@U18:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openevse
>>> print (openevse.WifiOpenEVSE('10.0.0.7').status())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gt/.local/lib/python3.6/site-packages/openevse.py", line 254, in status
    done, data = self._request('GS')
  File "/home/gt/.local/lib/python3.6/site-packages/openevse.py", line 898, in _request
    match = self.regex.match(resp.read())
TypeError: cannot use a string pattern on a bytes-like object

```

**Comment by vintozver** [comment]
python 3 encoding fun. will fix it

**Comment by stopeject** [comment]
Thanks.

**Comment by stopeject** [comment]
Sorry to bother you, I understand this is not a high priority project, butI'd like to know whether I should wait or try a different approach.

**Comment by tiramiseb** [comment]
@vintozver are you able to fix it? or maybe do you want me to check if I can do something?

**Comment by kernelkraut** [comment]
I'm also struggling with this library. Simple tests don't work for me. Serial doesn't work at all and wifi returns unexpected info. I can use screen to connect directly and everything works but nothing works through python. I noticed the openevse.py Serial section is trying to connect to AMA0 so I have changed that to the correct port (/dev/serial0) but it doesn't fix the issue. 

![image](https://user-images.githubusercontent.com/23164186/61781425-9c7c3a00-ae04-11e9-93e7-f319b010063d.png)


![image](https://user-images.githubusercontent.com/23164186/61781308-735ba980-ae04-11e9-9771-05096e0c54f0.png)

**Comment by tiramiseb** [comment]
I personally have stopped using this library months ago, and honestly I doubt I will use it again because I switched to Go as my favorite language.
I was glad to see that @vintozver could take over, but he doesn't seem very active. If anyone wants to help with this library, don't hesitate to tell so, I can give you RW access to the repository.
